# Generated by Django 3.1.3 on 2020-11-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201115_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='documentId',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='documentType',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='legalNature',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
