# Generated by Django 3.1.3 on 2020-12-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201121_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='legalNature',
            field=models.BooleanField(default=False),
        ),
    ]
