# Generated by Django 3.1.3 on 2020-12-16 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201212_1552'),
        ('app', '0004_auto_20201212_1949'),
    ]

    operations = [
    ]
