# Generated by Django 3.1.3 on 2020-12-16 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_merge_20201216_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='dateDonation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donorId',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='statusTransactionState',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='valueDonation',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
